export const MESSAGE_NAMES = {
  CREATE_GAME: "CREATE_GAME",
  JOIN_GAME: "JOIN_GAME",
  UPDATE_GAME: "UPDATE_GAME",
  PLAYER_JOIN: "PLAYER_JOIN",
  START_GAME: "START_GAME",
  GAME_OVER: "GAME_OVER",
};
